# Generated by Django 3.1 on 2021-02-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210227_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
