# Generated by Django 3.1 on 2021-02-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210227_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='quatity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
