# Generated by Django 3.1 on 2021-02-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
