# Generated by Django 3.1 on 2021-02-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210227_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
